#!/bin/sh

# Find the highest day value in the current directory
highest_day=0
for dir in day*; do
    if [[ -d "$dir" ]]; then
        day=${dir#day}
        if [[ $day =~ ^[0-9]+$ ]]; then
            if (( day > highest_day )); then
                highest_day=$day
            fi
        fi
    fi
done

# Calculate the next day value
next_day=$((highest_day + 1))

echo "Next day value: $next_day"
groupId="com.benjaminbinford"
artifactId="day${next_day}"
package="${groupId}.day${next_day}"
version="1.0-SNAPSHOT"

mvn install -pl dayArchetype && mvn archetype:generate -DarchetypeGroupId=com.benjaminbinford.aoc2023 -DarchetypeArtifactId=dayArchetype -DarchetypeVersion=1.0-SNAPSHOT -DgroupId="${groupId}" -DartifactId="${artifactId}" -Dpackage="${package}" -Dversion="${version}" -DinteractiveMode=false
